export const FETCH_USER = 'FETCH_USER'
export const GET_TICKETS =  'GET_TICKETS'
export const ALL_USERS = 'ALL_USERS'
export const GET_USER = 'GET_USER'
export const GET_WEATHER = 'GET_WEATHER'
export const GET_MESSAGES = 'GET_MESSAGES'
export const COMPOSE_MESSAGE = 'COMPOSE_MESSAGE'
